#!/bin/bash

BUILDROOT_VERSION="`cat \"${BUILD_DIRECTORY}/buildroot-version\"`"
ECHOCAT_NANO_VERSION="`cat \"${BUILD_DIRECTORY}/echocat-nano-version\"`"
MONGODB_VERSION="`cat \"${BUILD_DIRECTORY}/mongodb-version\"`"
SLEEP_BETWEEN_TAILS=5m
LINES_OF_TAILS=20

function print-tail-every {
	while [ true ]; do
		sleep $SLEEP_BETWEEN_TAILS
		log INFO "make is still ongoing. Output of the latest $LINES_OF_TAILS lines:"
		tail -n $LINES_OF_TAILS $1
		echo ""
	done
}

function prepare-buildroot-directory {
	execute mkdir -p "${BUILD_DIRECTORY}"
	execute cd "${BUILD_DIRECTORY}"
	checkForExecutable wget
	checkForExecutable tar
	execute wget -q "http://buildroot.uclibc.org/downloads/buildroot-${BUILDROOT_VERSION}.tar.gz" -O "buildroot-${BUILDROOT_VERSION}.tar.gz"
	execute tar -xzf "buildroot-${BUILDROOT_VERSION}.tar.gz"
	execute cp -f "${SOURCE_DIRECTORY}/buildroot.config" "${BUILD_DIRECTORY}/buildroot-${BUILDROOT_VERSION}/.config"

	execute wget -q "https://github.com/echocat/docker-nano/releases/download/v${ECHOCAT_NANO_VERSION}/toolchain.tar.gz" -O "${BUILD_DIRECTORY}/toolchain.tar.gz"
	execute mkdir -p "${BUILD_DIRECTORY}/buildroot-${BUILDROOT_VERSION}/output/host"
	execute cd "${BUILD_DIRECTORY}/buildroot-${BUILDROOT_VERSION}/output/host"
	execute tar -xzf "${BUILD_DIRECTORY}/toolchain.tar.gz"
}

function store-buildroot-artifacts {
	checkForExecutable tar
	checkForExecutable find

	execute rm -rf "${BUILD_DIRECTORY}/docker-intermediate-image"
	execute rm -rf "${BUILD_DIRECTORY}/docker-image"
	
	execute mkdir -p "${BUILD_DIRECTORY}/docker-intermediate-image"
	execute cd "${BUILD_DIRECTORY}/docker-intermediate-image"
	execute tar --exclude "./dev/*" -xzf "${BUILD_DIRECTORY}/buildroot-${BUILDROOT_VERSION}/output/images/rootfs.tar.gz"

	execute find "${BUILD_DIRECTORY}/docker-intermediate-image" -exec "${SOURCE_DIRECTORY}/build-buildroot-processRootFs" "{}" "${BUILD_DIRECTORY}/docker-intermediate-image" "${BUILD_DIRECTORY}/docker-depedency-image/root" "${BUILD_DIRECTORY}/docker-image" \;
	execute cd "${BUILD_DIRECTORY}/docker-image"
	execute "${SOURCE_DIRECTORY}/build-buildroot-postFileSystemBuild"

	execute tar -czf "${IMAGES_DIRECTORY}/rootfs.tar.gz" .
}

function build-buildroot {
	if [ -f "${BUILD_DIRECTORY}/skipBuild-buildroot" ] || [ -n "${SKIP_BUILD_BUILDROOT}" ]; then
		log INFO "Build of buildroot will be skipped."
	else
		prepare-buildroot-directory

		if [ "${CALL_BUILDROOT_MENU_CONFIG,,}" == "y" ]; then
			execute make menuconfig
			execute cp -f "${BUILD_DIRECTORY}/buildroot-${BUILDROOT_VERSION}/.config" "${SOURCE_DIRECTORY}/buildroot.config"
			exit 0
		fi
		execute cd "${BUILD_DIRECTORY}/buildroot-${BUILDROOT_VERSION}"
		log INFO "Start building of buildroot. This could take a while without any output. Output be gerenated on errors and every $SLEEP_BETWEEN_TAILS with the last $LINES_OF_TAILS lines."

		make "BR2_EXTERNAL=${SOURCE_DIRECTORY}/packages" "MONGODB_VERSION=${MONGODB_VERSION}" &> .build.log &
		local makePid=$!

		print-tail-every .build.log &
		local tailPid=$!

		wait $makePid
		local errorCode=$?
		kill $tailPid

		if [ $errorCode -ne 0 ]; then
			tail -n 50 .build.log 1>&2
			fail "While building buildroot an error was produced: $errorCode"
		fi
		log INFO "Build of buildroot done!"

		store-buildroot-artifacts
	fi
}
